<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="recipes">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="recipe" type="recipeType" minOccurs="1" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="recipeType">
        <xs:sequence>
            <xs:element name="title" type="xs:string"/>
            <xs:element name="cuisineTypes" type="cuisineTypesType"/>
            <xs:element name="difficultyLevel" type="difficultyLevelType"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:string" use="required"/>
    </xs:complexType>

    <xs:complexType name="cuisineTypesType">
        <xs:sequence>
            <xs:element name="cuisineType" type="xs:string" minOccurs="2" maxOccurs="2"/>
        </xs:sequence>
    </xs:complexType>

    <xs:simpleType name="difficultyLevelType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Beginner"/>
            <xs:enumeration value="Intermediate"/>
            <xs:enumeration value="Advanced"/>
        </xs:restriction>
    </xs:simpleType>

</xs:schema>
